#!/usr/bin/env bash
# Managed Fixer MCP installer entry point for the published repository.
#
# This is the single supported install path. It builds a release from this
# checkout, installs it into the managed root (versioned releases behind an
# atomic `current` symlink plus a `fixer` command shim), and keeps the release
# descriptor and payload it installed from under
# <managed root>/update-source/<version>/, which is what `fixer update` reads.
set -euo pipefail

# Keep the checkout free of generated bytecode while the managed modules run.
export PYTHONDONTWRITEBYTECODE=1

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python3}"
RELEASE_VERSION="${RELEASE_VERSION:-0.1.0}"
VERIFY=0

usage() {
  printf 'Usage: %s [--prefix PATH] [--version VERSION] [--verify]\n' "$0"
  printf '  --prefix PATH     install prefix: the command shim goes to <PATH>/bin\n'
  printf '  --version VERSION release version to build and install\n'
  printf '  --verify          run the managed installation verification afterwards\n'
}

while (($#)); do
  case "$1" in
    --prefix) FIXER_INSTALL_PREFIX="${2:?--prefix requires a path}"; shift 2 ;;
    --version) RELEASE_VERSION="${2:?--version requires a value}"; shift 2 ;;
    --verify) VERIFY=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) usage >&2; exit 2 ;;
  esac
done

# Managed locations. Shell startup files are never modified.
#   FIXER_MANAGED_ROOT     managed root (default: $HOME/.fixer)
#   FIXER_STATE_DIR        user state and database directory
#                          (default: $XDG_STATE_HOME/fixer-client-wires)
#   FIXER_USER_BIN         directory for the `fixer` command shim
#                          (default: $HOME/.local/bin)
#   FIXER_INSTALL_PREFIX   prefix shorthand for the shim directory: <prefix>/bin
MANAGED_ROOT="${FIXER_MANAGED_ROOT:-${HOME}/.fixer}"
if [[ -n "${FIXER_USER_BIN:-}" ]]; then
  BIN_DIR="${FIXER_USER_BIN}"
elif [[ -n "${FIXER_INSTALL_PREFIX:-}" ]]; then
  BIN_DIR="${FIXER_INSTALL_PREFIX}/bin"
else
  BIN_DIR="${HOME}/.local/bin"
fi
RELEASE_SOURCE_DIR="${FIXER_RELEASE_SOURCE_DIR:-${MANAGED_ROOT}/update-source/${RELEASE_VERSION}}"

export FIXER_MANAGED_ROOT="${MANAGED_ROOT}"
export FIXER_USER_BIN="${BIN_DIR}"

command -v go >/dev/null || { echo 'Go 1.25.4 or newer is required to build Fixer MCP.' >&2; exit 1; }
command -v "${PYTHON}" >/dev/null || { echo 'Python 3.12 or newer is required to build Fixer MCP.' >&2; exit 1; }

echo "Building Fixer MCP ${RELEASE_VERSION} release source"
echo "  release source: ${RELEASE_SOURCE_DIR}"
mkdir -p "${RELEASE_SOURCE_DIR}"
"${PYTHON}" "${ROOT_DIR}/scripts/release/assemble_release.py" \
  --repo-root "${ROOT_DIR}" \
  --out-dir "${RELEASE_SOURCE_DIR}" \
  --version "${RELEASE_VERSION}" >/dev/null

install_args=(
  --descriptor "${RELEASE_SOURCE_DIR}/release.json"
  --managed-root "${MANAGED_ROOT}"
  --bin-dir "${BIN_DIR}"
)
if [[ -n "${FIXER_STATE_DIR:-}" ]]; then
  install_args+=(--state-dir "${FIXER_STATE_DIR}")
fi

echo "Installing into ${MANAGED_ROOT}"
"${PYTHON}" "${ROOT_DIR}/scripts/install/install.py" "${install_args[@]}"

echo "The release source for 'fixer update' is kept at: ${RELEASE_SOURCE_DIR}"
case ":${PATH}:" in *":${BIN_DIR}:"*) ;; *) echo "Add ${BIN_DIR} to PATH to run 'fixer' directly (shell files were not modified)." ;; esac

if (( VERIFY )); then
  bash "${ROOT_DIR}/scripts/verify-install.sh"
fi
