#!/usr/bin/env bash
# Verification pass for a managed Fixer MCP installation.
#
# Checks the runtime behind the installed `fixer` command shim: version
# identity, doctor health, a clean MCP stdio initialization against a fresh
# database, and the self-update check that reads the recorded release source.
set -euo pipefail

# Keep the checkout free of generated bytecode while the managed modules run.
export PYTHONDONTWRITEBYTECODE=1

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-python3}"
MANAGED_ROOT="${FIXER_MANAGED_ROOT:-${HOME}/.fixer}"
if [[ -n "${FIXER_USER_BIN:-}" ]]; then
  BIN_DIR="${FIXER_USER_BIN}"
elif [[ -n "${FIXER_INSTALL_PREFIX:-}" ]]; then
  BIN_DIR="${FIXER_INSTALL_PREFIX}/bin"
else
  BIN_DIR="${HOME}/.local/bin"
fi
FIXER="${BIN_DIR}/fixer"
BINARY="${MANAGED_ROOT}/current/fixer_mcp/fixer_mcp"

test -x "${FIXER}" || { echo "Missing fixer command shim: ${FIXER}" >&2; exit 1; }
test -x "${BINARY}" || { echo "Missing installed Fixer MCP runtime: ${BINARY}" >&2; exit 1; }

echo "[verify] managed installation and command shim"
env -u FIXER_DB_PATH "${FIXER}" --version
env -u FIXER_DB_PATH "${FIXER}" doctor

echo "[verify] clean MCP stdio initialization on the installed runtime"
smoke_root="$(mktemp -d)"
trap 'rm -rf "${smoke_root}"' EXIT
env -u FIXER_DB_PATH -u FIXER_MCP_LOCKED_ROLE -u FIXER_MCP_DEFAULT_ROLE \
  -u FIXER_MCP_DEFAULT_CWD -u FIXER_MCP_AUTO_AUTH -u FIXER_MCP_TOOL_PROFILE \
  FIXER_SMOKE_BINARY="${BINARY}" \
  FIXER_SMOKE_ROOT="${smoke_root}" \
  FIXER_SMOKE_DB_PATH="${smoke_root}/runtime/fixer.db" \
  "${PYTHON}" "${ROOT_DIR}/tests/fixer_mcp_stdio_smoke.py"

echo "[verify] self-update check against the recorded release source"
env -u FIXER_DB_PATH "${FIXER}" update --check

echo "Fixer MCP managed installation verified."
