development:
  database: 'fixer-dashboard-dev'
  redis: 'fixer-dashboard-redis-dev'
  serviceSecret: 'fixer-dashboard-service-dev'

test:
  database: 'fixer-dashboard-test'
  redis: 'fixer-dashboard-redis-test'
  serviceSecret: 'fixer-dashboard-service-test'

staging:
  database: 'replace-me'
  serviceSecret: 'replace-me'

production:
  database: 'replace-me'
  serviceSecret: 'replace-me'
